New log file opened at Sat May 30 15:13:06 JST 2015 by 7204@kengo-PCn
Taking next connection to: 61574
New client attempting to connect on port: 61576-61574
  Address = /192.168.169.1:61574
This client on port 61576 has uuid 7f0d8f63-d40e-4721-bdc4-be7f29c609ca configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-7f0d8f63-d40e-4721-bdc4-be7f29c609ca
Taking next connection to: 61574
New client attempting to connect on port: 61577-61574
  Address = /192.168.169.1:61574
Handshake exception on socket: 61577
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 61574
New client attempting to connect on port: 61578-61574
  Address = /192.168.169.1:61574
This client on port 61578 has uuid 33eac2ee-735f-4695-9dc4-f9bbd2953036 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-7f0d8f63-d40e-4721-bdc4-be7f29c609ca, activator-33eac2ee-735f-4695-9dc4-f9bbd2953036
Taking next connection to: 61574
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 61574
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 61574
New client attempting to connect on port: 61611-61574
  Address = /192.168.169.1:61574
Handshake exception on socket: 61611
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 61574
New client attempting to connect on port: 61612-61574
  Address = /192.168.169.1:61574
This client on port 61612 has uuid 5aa5a8f0-7cf6-47ae-b925-7f690e1407f1 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-33eac2ee-735f-4695-9dc4-f9bbd2953036, play-fork-run-5aa5a8f0-7cf6-47ae-b925-7f690e1407f1
Taking next connection to: 61574
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 61574
